# Generated by Django 3.2 on 2022-12-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default=0, max_length=254),
        ),
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(default=0, max_length=128),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date_time',
            field=models.DateField(auto_now=True),
        ),
    ]
