# Generated by Django 3.2 on 2022-12-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20221207_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default=0, max_length=254)),
                ('password', models.CharField(default=0, max_length=128)),
                ('name', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
