# Generated by Django 3.2 on 2022-12-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_auto_20221207_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='dishes',
            field=models.ManyToManyField(related_name='foods', through='restaurant.Order', to='restaurant.Ingredient'),
        ),
    ]
